project_id = "nkksaglvokypjwnavasb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
jwt_expiry = 3600
site_url = "https://nuevageneracion.lovable.app"
additional_redirect_urls = ["https://nuevageneracion.lovable.app", "http://localhost:8080"]
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true

[functions.validate-admin]
verify_jwt = false