// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkksaglvokypjwnavasb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ra3NhZ2x2b2t5cGp3bmF2YXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjUzMDEsImV4cCI6MjA3Mzc0MTMwMX0.8Ly98I3CYjSI7dQF_m51phM9UkCvfST5sCZ6-22xdxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});